name: wofkflow_cluster
on:
    push:
      branches:
          - 'dt/**'

jobs:

    infrastructure_vulnerability_scanning:
        uses: 5gplustactile/provisioning/.github/workflows/workflow-terrascan-tf.yaml@pipelines
        secrets:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    iac:
        uses: 5gplustactile/provisioning/.github/workflows/workflow-iac-aws.yaml@pipelines
        needs: infrastructure_vulnerability_scanning
        secrets:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            OPS_AWS_ACCESS_KEY_ID: ${{ secrets.OPS_AWS_ACCESS_KEY_ID }}
            OPS_AWS_SECRET_ACCESS_KEY: ${{ secrets.OPS_AWS_SECRET_ACCESS_KEY }}
            OPS_AWS_REGION: ${{ secrets.OPS_AWS_REGION }}
            SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
            SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
    
    cluster_as_code:
        needs: iac
        uses: 5gplustactile/provisioning/.github/workflows/workflow-cluster.yaml@pipelines
        secrets:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            ARGOCD_HOSTNAME: ${{ secrets.ARGOCD_HOSTNAME }}
            ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
            GIT_REPO: ${{ secrets.GIT_REPO }}

    cluster_vulnerability_scanning:
        needs: cluster_as_code
        uses: 5gplustactile/provisioning/.github/workflows/workflow-terrascan-k8s.yaml@pipelines
        secrets:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}