name: provisioning cluster
on:
  workflow_call:
    secrets:
        ACCESS_TOKEN:
          required: true
        ARGOCD_HOSTNAME:
          required: true
        ARGOCD_PASSWORD:
          required: true
        GIT_REPO:
          required: true
jobs:
    provisioning:
        name: provisioning
        runs-on: self-hosted
        env:
          CI_COMMIT_MESSAGE: creating manifiest to create clusters
          ARGOCD_HOSTNAME: argocd-server.argocd.svc.cluster.local
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            repository: '5gplustactile/provisioning'
            ref: ${{ github.head_ref }}
            fetch-depth: 0
            token: ${{ secrets.ACCESS_TOKEN }}

        # extract branch name
        - name: Extract branch name
          shell: bash
          run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          id: extract_branch

        - name: Get branch name
          run: echo 'The branch name is' ${{ steps.extract_branch.outputs.branch }}

        - name: Installing dependencies
          run: |  
           echo "### install yq ###"
           sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
           sudo chmod a+x /usr/local/bin/yq
           yq --version

           echo "### install jq ###"
           sudo apt install jq -y
           jq --version

           echo "## install gh ###"
           type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
           curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
           && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
           && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
           && sudo apt update \
           && sudo apt install gh -y

           # get the latest version or change to a specific version
           VERSION=$(curl --silent "https://api.github.com/repos/argoproj-labs/argocd-autopilot/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
           # download and extract the binary
           curl -L --output - https://github.com/argoproj-labs/argocd-autopilot/releases/download/$VERSION/argocd-autopilot-linux-amd64.tar.gz | tar zx
           # move the binary to your $PATH
           sudo mv ./argocd-autopilot-* /usr/local/bin/argocd-autopilot
           # check the installation
           argocd-autopilot version

           echo "### argocd ###"
           # download
           curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
           # install
           sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
           # delete package
           rm argocd-linux-amd64

        - name: create Pull Request
          env:
            TARGET_BRANCH: main
            TITLE: "creating/deleting manifiest to deploy/destroy cluster"
            BODY: "Created by GitHub Actions"
            REVIEWER: "andresanaya21"
            ASSIGNED: "andresanaya21"
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          run: |
            #!/bin/bash          
            while :
              do
                 if gh pr create -B ${{ env.TARGET_BRANCH }} -H ${{ steps.extract_branch.outputs.branch }} --title '${{ env.TITLE }}' --body '${{ env.BODY }}' \
                 --reviewer "${{ env.REVIEWER }}" --assignee ${{ env.ASSIGNED }} 2>/dev/null; then
                    echo "pull request created"
                    exit 0;
                  else
                    echo "skipping"
                    exit 0;
                 fi
              done

        - name: pulling repository 5gplustactile/auto-ztp
          uses: actions/checkout@v3
          with:
            repository: '5gplustactile/auto-ztp'
            ref: main
            fetch-depth: 0
            token: ${{ secrets.ACCESS_TOKEN }}

        - name: Getting variable branch
          run: |
           echo "BRANCH=$(echo ${{ steps.extract_branch.outputs.branch }} | cut -d/ -f2)" >> $GITHUB_ENV

        - name: targetRevision of helm chart
          run: |
           echo "### modifying targetRevision ###"
           yq e '.spec.sources[1].targetRevision="${{ steps.extract_branch.outputs.branch }}"' -i sites/${{ env.BRANCH }}/edge/app.yaml
           yq eval '.metadata.name = "clusters-${{ env.BRANCH }}-edge-clusters"' -i sites/${{ env.BRANCH }}/edge/app.yaml
           yq eval '.spec.destination.namespace = "${{ env.BRANCH }}"' -i sites/${{ env.BRANCH }}/edge/app.yaml
           yq eval '.spec.sources[0].helm.valueFiles[0] = "$values/${{ env.BRANCH }}/edge/values.yaml"' -i sites/${{ env.BRANCH }}/edge/app.yaml

           cp -pr templates/helm-edge-chart/ sites/${{ env.BRANCH }}/edge
           yq eval '.name = "${{ env.BRANCH }}-edge"' -i sites/${{ env.BRANCH }}/edge/helm-edge-chart/Chart.yaml
           
           
           yq e '.spec.sources[1].targetRevision="${{ steps.extract_branch.outputs.branch }}"' -i sites/${{ env.BRANCH }}/region/app.yaml
           yq eval '.metadata.name = "clusters-${{ env.BRANCH }}-region-clusters"' -i sites/${{ env.BRANCH }}/region/app.yaml
           yq eval '.spec.destination.namespace = "${{ env.BRANCH }}"' -i sites/${{ env.BRANCH }}/region/app.yaml
           yq eval '.spec.sources[0].helm.valueFiles[0] = "$values/${{ env.BRANCH }}/region/values.yaml"' -i sites/${{ env.BRANCH }}/region/app.yaml

           cp -pr templates/helm-region-chart/ sites/${{ env.BRANCH }}/region
           yq eval '.name = "${{ env.BRANCH }}-region"' -i sites/${{ env.BRANCH }}/region/helm-region-chart/Chart.yaml
           
           yq e '.spec.sources[1].targetRevision="${{ steps.extract_branch.outputs.branch }}"' -i sites/${{ env.BRANCH }}/wavelength/app.yaml
           yq eval '.metadata.name = "clusters-${{ env.BRANCH }}-wavelength-clusters"' -i sites/${{ env.BRANCH }}/wavelength/app.yaml
           yq eval '.spec.destination.namespace = "${{ env.BRANCH }}"' -i sites/${{ env.BRANCH }}/wavelength/app.yaml
           yq eval '.spec.sources[0].helm.valueFiles[0] = "$values/${{ env.BRANCH }}/wavelength/values.yaml"' -i sites/${{ env.BRANCH }}/wavelength/app.yaml

           cp -pr templates/helm-wavelength-chart/ sites/${{ env.BRANCH }}/wavelength
           yq eval '.name = "${{ env.BRANCH }}-wavelength"' -i sites/${{ env.BRANCH }}/wavelength/helm-wavelength-chart/Chart.yaml

           echo NAME_ARGOCD_APP_EDGE=$(yq e '.metadata.name' sites/${{ env.BRANCH }}/edge/app.yaml) >> $GITHUB_ENV
           echo NAME_ARGOCD_APP_REGION=$(yq e '.metadata.name' sites/${{ env.BRANCH }}/region/app.yaml) >> $GITHUB_ENV
           echo NAME_ARGOCD_APP_WAVELENGTH=$(yq e '.metadata.name' sites/${{ env.BRANCH }}/wavelength/app.yaml) >> $GITHUB_ENV
           
        - name: commit changes in 5gplustactile/auto-ztp repository
          run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"  
           git add .
           git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}" --allow-empty
  
        - name: push changes in 5gplustactile/auto-ztp repository
          uses: ad-m/github-push-action@master
          with:
            branch: main
            repository: '5gplustactile/auto-ztp'
            github_token: ${{ secrets.ACCESS_TOKEN }}

        - name: creating app in argocd - edge
          env:
            ENVIRON: edge
          run: |
           #!/bin/bash
           export GIT_TOKEN=${{ secrets.ACCESS_TOKEN }}
           export GIT_REPO=${{ secrets.GIT_REPO }}
           while :
           do
              if argocd-autopilot app create ${{ env.BRANCH }}/${{ env.ENVIRON }} --app github.com/5gplustactile/auto-ztp/sites/${{ env.BRANCH }}/${{ env.ENVIRON }}?ref=main -p clusters --type dir --type dir; then
                 echo "app created"
                 exit 0;
               else
                exit 0;
              fi 
           done

        - name: creating app in argocd - region
          env:
            ENVIRON: region
          run: |
           #!/bin/bash
           export GIT_TOKEN=${{ secrets.ACCESS_TOKEN }}
           export GIT_REPO=${{ secrets.GIT_REPO }}
           while :
           do
              if argocd-autopilot app create ${{ env.BRANCH }}/${{ env.ENVIRON }} --app github.com/5gplustactile/auto-ztp/sites/${{ env.BRANCH }}/${{ env.ENVIRON }}?ref=main -p clusters --type dir --type dir; then
                 echo "app created"
                 exit 0;
               else
                exit 0;
              fi 
           done

        - name: creating app in argocd - wavelength
          env:
            ENVIRON: wavelength
          run: |
           #!/bin/bash
           export GIT_TOKEN=${{ secrets.ACCESS_TOKEN }}
           export GIT_REPO=${{ secrets.GIT_REPO }}
           while :
           do
              if argocd-autopilot app create ${{ env.BRANCH }}/${{ env.ENVIRON }} --app github.com/5gplustactile/auto-ztp/sites/${{ env.BRANCH }}/${{ env.ENVIRON }}?ref=main -p clusters --type dir --type dir; then
                 echo "app created"
                 exit 0;
               else
                exit 0;
              fi 
           done

        - name: checking iac repository 5gplustactile/iac
          uses: actions/checkout@v3
          with:
            repository: '5gplustactile/iac'
            ref: main
            fetch-depth: 0
            token: ${{ secrets.ACCESS_TOKEN }}

        - name: appName and useGivenName - edge
          env:
            ENVIRON: edge
            APPNAME: edge-clusters
          run: |
           jq '.appName="${{ env.BRANCH }}-${{ env.APPNAME }}"' apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.json > apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template
           jq '.userGivenName="${{ env.BRANCH }}-${{ env.APPNAME }}"' apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template > apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.json
           rm -rf apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template
           
        - name: appName and useGivenName - region
          env:
            ENVIRON: region
            APPNAME: region-clusters
          run: |
           jq '.appName="${{ env.BRANCH }}-${{ env.APPNAME }}"' apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.json > apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template
           jq '.userGivenName="${{ env.BRANCH }}-${{ env.APPNAME }}"' apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template > apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.json
           rm -rf apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template

        - name: appName and useGivenName - wavelength
          env:
            ENVIRON: wavelength
            APPNAME: wavelength-clusters
          run: |
           jq '.appName="${{ env.BRANCH }}-${{ env.APPNAME }}"' apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.json > apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template
           jq '.userGivenName="${{ env.BRANCH }}-${{ env.APPNAME }}"' apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template > apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.json
           rm -rf apps/${{ env.BRANCH }}/${{ env.ENVIRON }}/clusters/config_dir.template


        - name: commit changes in 5gplustactile/iac repository
          run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"  
           git add .
           git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}" --allow-empty
  
        - name: push changes in 5gplustactile/iac repository
          uses: ad-m/github-push-action@master
          with:
            branch: main
            repository: '5gplustactile/iac'
            github_token: ${{ secrets.ACCESS_TOKEN }}

        - name: argocd edge - pre-deploy
          run: |
           argocd login --username admin --password ${{ secrets.ARGOCD_PASSWORD }}  ${{ env.ARGOCD_HOSTNAME }} --insecure
           argocd app sync ${{ env.NAME_ARGOCD_APP_EDGE }} --dry-run

        - name: argocd edge - review difference against the target and live state before syncing app
          run: |
           argocd login --username admin --password ${{ secrets.ARGOCD_PASSWORD }}  ${{ env.ARGOCD_HOSTNAME }} --insecure
           echo "n" | argocd app sync ${{ env.NAME_ARGOCD_APP_EDGE }}  --preview-changes

        - name: argocd region - pre-deploy
          run: |
           argocd login --username admin --password ${{ secrets.ARGOCD_PASSWORD }}  ${{ env.ARGOCD_HOSTNAME }} --insecure
           argocd app sync ${{ env.NAME_ARGOCD_APP_REGION }} --dry-run

        - name: argocd region - review difference against the target and live state before syncing app
          run: |
           argocd login --username admin --password ${{ secrets.ARGOCD_PASSWORD }}  ${{ env.ARGOCD_HOSTNAME }} --insecure
           echo "n" | argocd app sync ${{ env.NAME_ARGOCD_APP_REGION }}  --preview-changes

#        - name: argocd wavelength - pre-deploy
#          run: |
#           argocd login --username admin --password ${{ secrets.ARGOCD_PASSWORD }}  ${{ env.ARGOCD_HOSTNAME }} --insecure
#           argocd app sync ${{ env.NAME_ARGOCD_APP_WAVELENGTH }} --dry-run
#
#        - name: argocd wavelength - review difference against the target and live state before syncing app
#          run: |
#           argocd login --username admin --password ${{ secrets.ARGOCD_PASSWORD }}  ${{ env.ARGOCD_HOSTNAME }} --insecure
#           echo "n" | argocd app sync ${{ env.NAME_ARGOCD_APP_WAVELENGTH }}  --preview-changes           